### ISSUE TITLE
Firmware update Mac OS? 

### ISSUE THREAD

**Issue by jasonsee** [Atarity/Lightpack-docs#2]
https://github.com/Atarity/Lightpack-docs/blob/master/EN/Lightpack_firmware_update_with_FLIP_utility.md

Not seeing any solutions here for Mac OS firmware update.

**Comment by IamWJC** [comment]
Would also like to know how to do this! Any news?

**Comment by Atarity** [comment]
Sorry guys, but this repo is deprecated ([more info](http://atarity.ru/post/85837330541/after-three-years-we-leave-our-lightpack)). All up-to-date topics published on [https://github.com/woodenshark/Lightpack-docs](https://github.com/woodenshark/Lightpack-docs) (but, actually, it seems still not updated yet). I'm unable to help you with this. But you, of couse, can contact with [lightpack.tv support](http://lightpack.tv/contact) for help.
