### ISSUE TITLE
Using Two Lightpacks Simultaneously

### ISSUE THREAD

**Issue by pascalandy** [Atarity/Lightpack-docs#3]
Hi,

I'm trying to find documentation about using two lightpack. Can you please point out where is the documentation about this scanerio.

Cheers!
Pascal

**Comment by pascalandy** [comment]
OK, I only had to re-run the configuration wizard. It's all cool !
<img width="605" alt="screen shot 2015-10-03 at 4 59 44 pm" src="https://cloud.githubusercontent.com/assets/6694151/10265099/38617b54-69f0-11e5-99ba-99ff807b3f0c.png">

**Comment by pascalandy** [comment]
This should still be in the doc somewhere.

Cheers!
P

**Comment by Atarity** [comment]
It's good you handle problem by yourself. Yes — it's that simple. Actually, we can't to maintain project documentation cause the initial Lightpack team and I leaved the project more than 1.5 years ago. The whole Prismatik docs need to be updated.

**Comment by pascalandy** [comment]
It's an amazing project you did start here.
Cheers!
