### ISSUE TITLE
Problem with my light pack 

### ISSUE THREAD

**Issue by shant32** [Atarity/Lightpack-docs#8]
I have a gen 1 light pack I was in your kickstarter program and I bought the 10 leds and for some reason the blue hue isn’t working but every other color works I’m not really sure what’s wrong.

**Comment by Atarity** [comment]
Hi, this is the legacy repo with Lightpack documentation. Unfortunately, we unable to support you due to all of this repo mainteiners is out of the Laitpack project for more than 6 years. All support requests should be directed to [support page of lightpack.tv](https://lightpack.tv/pages/support)

**Comment by shant32** [comment]
Nothing you guys can do?

**Comment by Atarity** [comment]
@shant32 I'm afraid no. If you solder smth by yourself I bet 10 to 1  the problem in contacts (low-quality soldering) If you bought ready-made LEDs, maybe they just have defects (actually it is the same problem of the absence of contact).

**Comment by shant32** [comment]
So what do you suggest I do?

**Comment by Atarity** [comment]
@shant32 if you DIYed smth on your own and didn't bought additional products from lightpack.tv — double and triple check all connections and soldering points first. If you are talking about pre-made LED strips which you obtain from lightpack.tv — drop a line to their support team.
